language: ruby
sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install:
  - gem install bundler -v '~> 1.10'

gemfile:
  - gemfiles/rails_4_2.gemfile
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile
  - gemfiles/rails_master.gemfile

matrix:
  fast_finish: true
  # Run Danger only once
  include:
    - rvm: 2.5
      gemfile: gemfiles/rails_5_2.gemfile
      script: bundle exec danger
    - rvm: 2.3
      before_install:
        - gem install bundler -v '1.17.3'
      script: bundle _1.17.3_ exec rake
  exclude:
    - gemfile: gemfiles/rails_5_0.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_5_1.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_5_2.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.1
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.2
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.3
    - gemfile: gemfiles/rails_master.gemfile
      rvm: 2.4
  allow_failures:
    - gemfile: gemfiles/rails_master.gemfile
    - rvm: ruby-head
